name: ai_redakcia_frontend
description: Flutter frontend files bundle (3-page slide UI).
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.2.1
  dio: ^5.9.1
  shared_preferences: ^2.5.4
  file_selector: ^1.1.0
  super_clipboard: ^0.9.1
  freezed: ^3.2.5
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
dev_dependencies:
  json_serializable: ^6.13.0
